#!/usr/bin/env python3
"""okf_history.py - hashed, tiered commit-history doc (MEM-OKF style).

Tier-0 = a LUT of commits; the git short-hash IS the content address. Dig deeper
via `git show <hash>` (git is the tier-2 store). An agent reads the small LUT in
context and follows a hash only when it needs the full commit. No deps.
"""
import subprocess, sys, argparse, datetime, os, re

def git(repo, *args):
    r = subprocess.run(["git", "-C", repo, *args], capture_output=True, text=True, encoding="utf-8", errors="replace")
    return r.stdout

def gen(repo, out, n):
    name = os.path.basename(os.path.abspath(repo))
    head = git(repo, "rev-parse", "--short", "HEAD").strip()
    total = git(repo, "rev-list", "--count", "HEAD").strip()
    fmt = "%h\x1f%ad\x1f%s"
    log = git(repo, "log", "--pretty=" + fmt, "--date=short", "-" + str(n)).splitlines()
    rows = []
    for line in log:
        parts = line.split("\x1f")
        if len(parts) != 3:
            continue
        h, d, s = parts
        gate = ""
        m = re.search(r"(G-[A-Z0-9\-\.]+|GREEN)", s)
        if m:
            gate = m.group(1)
        rows.append((h, d, gate, s.replace("|", "/")))
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    fm = (
        "---\n"
        "type: log\n"
        "title: \"HISTORY - " + name + " (hashed tiered commit log)\"\n"
        "description: \"Tier-0 LUT of " + name + " milestones. The git short-hash is the content address; dig deeper via git show <hash> (git is the tier-2 store). Generated by tools/okf_history.py.\"\n"
        "tags: [history, log, mem-okf, " + name + "]\n"
        "timestamp: " + now + "\n"
        "resource: tools/okf_history.py\n"
        "sp_status: ACTIVE\n"
        "sp_gate: none\n"
        "sp_commit: " + head + "\n"
        "sp_repro: \"python tools/okf_history.py gen --repo . --out HISTORY.md\"\n"
        "---\n\n"
        "# HISTORY - " + name + "\n\n"
        "HEAD `" + head + "` * " + total + " commits total * generated " + now + ".\n\n"
        "**Tier-0 LUT** - the short-hash IS the content address. Follow any row with `git show <hash>` for the full commit (git = the tier-2 store). Gate/GREEN commits are tagged.\n\n"
        "| hash | date | gate | subject |\n|---|---|---|---|\n"
    )
    body = "".join("| `" + h + "` | " + d + " | " + g + " | " + s + " |\n" for (h, d, g, s) in rows)
    with open(out, "w", encoding="utf-8") as f:
        f.write(fm + body + "\n")
    print("wrote " + out + ": " + str(len(rows)) + " commits, HEAD " + head)

def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("gen")
    p.add_argument("--repo", default=".")
    p.add_argument("--out", default="HISTORY.md")
    p.add_argument("--n", type=int, default=80)
    a = ap.parse_args()
    gen(a.repo, a.out, a.n)

if __name__ == "__main__":
    main()